#################################################################
#
# file: Makefile
#
# @Author:    Ioannis Chatziantwoiou
# @Version:   26-11-2024
# @Email:     csd5193@csd.uoc.gr
#
#################################################################

all : test

test: test.c
	gcc test.c -o test

clean:
	rm -f test
